logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%5p) %clr(-){faint} %clr(%-80.80logger{79}){cyan} %clr(:) %m%n"

---
spring:
  application:
    name: eurekaServer
  profiles:
    active: dev
server:
  port: 3000
---
spring:
    application:
        name: eurekaServer
    profiles:
        active: stg
server:
  port: 3001
